ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS photo_url_1 VARCHAR(2048),
  ADD COLUMN IF NOT EXISTS photo_url_2 VARCHAR(2048),
  ADD COLUMN IF NOT EXISTS photo_url_3 VARCHAR(2048);
